services:
  db:
    image: postgres:16
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/1}
volumes:
  pgdata:
  redisdata:
