services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-fakestore}
      POSTGRES_USER: ${POSTGRES_USER:-fakestore}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-fakestore}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
  web:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    env_file:
      - ../.env.example
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app/backend
    environment:
      REDIS_URL: ${REDIS_URL:-redis://redis:6379/1}
volumes:
  pgdata:
  redisdata:
