# Generated by Django 4.2.25 on 2025-10-12 12:21

from django.db import migrations


def copy_name_fields(apps, schema_editor):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        update_fields = []
        first = getattr(user, "firstname", None)
        last = getattr(user, "lastname", None)
        if first is not None and first != user.first_name:
            user.first_name = first
            update_fields.append("first_name")
        if last is not None and last != user.last_name:
            user.last_name = last
            update_fields.append("last_name")
        if update_fields:
            user.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_email"),
    ]

    operations = [
        migrations.RunPython(copy_name_fields, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="user",
            name="firstname",
        ),
        migrations.RemoveField(
            model_name="user",
            name="lastname",
        ),
    ]
