# Generated by Django 4.2.25 on 2025-11-12 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_add_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("tr", "Turkish")], max_length=10
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product translation",
                "verbose_name_plural": "Product translations",
                "indexes": [
                    models.Index(
                        fields=["language"], name="product_translation_lang_idx"
                    )
                ],
                "unique_together": {("product", "language")},
            },
        ),
        migrations.CreateModel(
            name="CategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("tr", "Turkish")], max_length=10
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category translation",
                "verbose_name_plural": "Category translations",
                "indexes": [
                    models.Index(
                        fields=["language"], name="category_translation_lang_idx"
                    )
                ],
                "unique_together": {("category", "language")},
            },
        ),
    ]
